[package]
name = "day_one"
version = "0.1.0"
authors = ["William Stewart <zoidbergwill@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
